approvedGitRepositories:
  - "**"

enableScripts: false
nodeLinker: node-modules
checksumBehavior: throw
enableImmutableInstalls: true
enableTelemetry: false

# Block packages published within the past 7 days
npmMinimalAgeGate: 7
